# -*- coding: utf-8 -*-
"""logistic regression modell2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HZ-E4ECpSMXqlKYfEV8DMulCPUtBXCYU
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score

data = pd.read_csv("/titanic.csv")
data

df = data.info() 
df

df2 = data.describe()
df2

data.head()

data.tail()

data["Age"] = data["Age"].fillna(29.69)
data

x = data["Age"]
y = data["Survived"]

plt.scatter(x,y,color="purple")
plt.xlabel("Age")
plt.ylabel("Survived")
plt.show()

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=101)
x_train

x_test

y_train

y_test

model=LogisticRegression()
model.fit(x_train.values.reshape(-1,1),y_train)

predict1=model.predict(x_test.values.reshape(-1,1))
score=accuracy_score(y_test,predict1)
score